### ISSUE TITLE
Ruby identation of conditions within assignments

### ISSUE THREAD

**Issue by naps62** [subvisual/guides#5]
The setting we currently have in Rubocop enforces this:

``` ruby
value = if condition
          1
        else
          2
        end
```

Personally, I like it, but I believe some people prefer the other option:

``` ruby
value = if condition
  1
else
  2
end
```

My only issue with changing is that vim's auto-indent currently does the first option. If we change rubocop, we need to change vim as well, which I don't know how to do.

This was created because @zamith and I started this discussion during a code review.

PS: let's please not start a discussion about which one is better or why, and just focus on the decision and the vim issue :panda_face:

**Comment by zamith** [comment]
Actually I would indent the second version two spaces more, like I did in
the issue.

That is the version I prefer, but I have no problem with any of them.
