### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lordofthedanse** [subvisual/guides#7]
"decifer" should be spelled "decipher"

**Comment by zamith** [comment]
Thanks!

**Comment by lordofthedanse** [comment]
You got it!

On Tue, Sep 29, 2015 at 11:52 PM, Luís Ferreira notifications@github.com
wrote:

> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/subvisual/guides/issues/7#issuecomment-144213728.

## 

This e-mail message and any attachment to this e-mail message contains confidential information that may be legally privileged and/or deemed to be material non-public information.  The recipient may not reproduce, copy or forward (whether electronically or otherwise) any of the information or materials contained herein to any other person, except to the receiver's professional advisors.  If you are not the intended recipient, you must not review, retransmit, convert to hard copy, copy, use or disseminate this e-mail or any attachments to it. If you have received this e-mail in error, please immediately notify us by return e-mail and delete this message. E-mail transmissions cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.  The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission. If this e-mail contains a forwarded message or is a reply to a prior message, the sender may not have produced some or all of the contents of this message or any attachments. If verification is required, please request a hard-copy version.
